version: 0.2  
phases:  
  install:
    commands:
      - aws cloudformation package --template-file index-photos.yaml --s3-bucket photos-frontend-artifact --output-template-file photo-album-lambda.yaml
artifacts:  
  type: zip
  files:
    - photo-album-lambda.yaml
