AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  indexphotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: ./lambda zips/LF1-source/lambda_function.py
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::587787576424:role/lambda-s3-role'
      
  photosbackend:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: ./lambda zips/LF2-source/lambda_function.py
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::587787576424:role/lambda-s3-role'
  ElasticSearchCluster:
    Type: 'AWS::Elasticsearch::Domain'
    Properties:
      AccessPolicies:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
               arn:aws:iam::587787576424:role/aws-service-role/es.amazonaws.com/AWSServiceRoleForAmazonElasticsearchService
            Action: 'es:*'
            Resource: 'arn:aws:es:us-east-1:587787576424:domain/photos/*'
      DomainEndpointOptions:
        EnforceHTTPS: true
      DomainName: photos1
      EBSOptions:
        EBSEnabled: true
        VolumeSize: 10
        VolumeType: gp2
      ElasticsearchClusterConfig:
        InstanceType: t3.small.elasticsearch
      ElasticsearchVersion: '7.9'
      EncryptionAtRestOptions:
        Enabled: true
        KmsKeyId: 6a9529d4-515e-49d8-a98e-e3ed5c4cfcab
      NodeToNodeEncryptionOptions:
        Enabled: true
