AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  indexphotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: ./lambda zips/LF1-source/
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::587787576424:role/lambda-s3-role'
      
  photosbackend:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: ./lambda zips/LF2-source/
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::587787576424:role/lambda-s3-role'
